services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/docker/sonarr/data:/config
      - /var/plex/tv:/tv #optional
      - /var/plex/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/docker/radarr/data:/config
      - /var/plex/movies:/movies #optional
      - /var/plex/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/docker/bazarr/config:/config
      - /var/plex/movies:/movies #optional
      - /var/plex/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "container:/gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8085
    volumes:
      - /var/docker/qbittorrent/appdata/config:/config
      - /var/plex/downloads:/downloads #optional
    depends_on:
      - gluetun
    restart: always
    
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
    - /dev/net/tun:/dev/net/tun
    ports:
    - 6881:6881
    - 6881:6881/udp 
    - 8085:8085 #qbittorrent gui
    
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=88888888888888888888888888888
      - SERVER_CITIES=Amsterdam
      
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/docker/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /var/docker/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
